### ISSUE TITLE
Saving Outputs to a shared env

### ISSUE THREAD

**Issue by Jearonson** [santolucito/travelapp#4]
rather than downloading can we write file outputs to a shared drive? Google as a stopgap? that way you can see them too.
we need to be able to collaborate on troubleshooting behavior easily- i think a shared drive would be a better reference strategy rather than emailing downloaded files etc

**Comment by santolucito** [comment]
the download all descriptions button can be used, then upload that to a shared drive. closing for now becaus out of scope for current prototype - we can reopen later if needed
